view_event = {
	DRAG_ON = "VIEW_DRAG_ON",
	DRAG_OFF = "VIEW_DRAG_OFF",
	HOVER_ON = "VIEW_HOVER_ON",
	HOVER_OFF = "VIEW_HOVER_OFF",
	POOL_CHANGED = "VIEW_POOL_CHANGED",
	POOL_ASKS_UPDATE = "VIEW_POOL_ASKS_UPDATE",
	MODEL_CHANGED = "VIEW_MODEL_CHANGED",
	MODEL_ENTRIES_CHANGED = "VIEW_MODEL_ENTRIES_CHANGED", -- function(entry_count)
	FLEX_SIZE_CHANGED = "VIEW_FLEX_SIZE_CHANGED", -- function(size_y)
	INPUT_CLOSE = "VIEW_INPUT_CLOSE",
}